// <auto-generated />
namespace BuyOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddToCart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddToCart));
        
        string IMigrationMetadata.Id
        {
            get { return "202305180748250_AddToCart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
